# Generated by Django 3.1.2 on 2021-11-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211101_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
