# Generated by Django 3.2.8 on 2021-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211101_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.CharField(default='whatever', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
